### ISSUE TITLE
Need a test/fix for internal mediawiki style links with double square brackets '[[', ']]'

### ISSUE THREAD

**Issue by ArtskydJ** [ArtskydJ/noddity-render-dom#12]
```js
new Ractive({
    staticDelimiters: [ '{{{{', '}}}}' ],
    staticTripleDelimiters: [ '{{{{{', '}}}}}' ]
})
// or whatever we decide
```

**Comment by TehShrike** [comment]
maybe `[[static]] stuff [[/static]]`?

**Comment by TehShrike** [comment]
Same issue for the static renderer: https://github.com/TehShrike/noddity-render-static/issues/10

**Comment by ArtskydJ** [comment]
I feel like `[[static]] stuff [[/static]]` is weirdly close to the linkifier's `[[post]]` format.

I don't know what else to make it though...

**Comment by ArtskydJ** [comment]
https://github.com/ractivejs/ractive/issues/2240
