### ISSUE TITLE
First load is slow

### ISSUE THREAD

**Issue by ArtskydJ** [ArtskydJ/noddity-render-dom#19]
See if it is waiting for all the posts to load. It shouldn't be, but it might be.

**Comment by ArtskydJ** [comment]
@TehShrike Have we not published the fix for this yet?

**Comment by TehShrike** [comment]
oh snap!

**Comment by TehShrike** [comment]
Oh no, this one got published as 3.0.1 - it's #22 that hasn't been published yet
